module.exports = {
  REWARDS_RECEIVED: "REWARDS_RECEIVED",
  REWARD_RECEIVED: "REWARD_RECEIVED",
  REWARD_REMOVED: "REWARD_REMOVED",
  REWARD_FORM_ITEMS_RECEIVED: "REWARD_FORM_ITEMS_RECEIVED",
  REWARD_FORM_ITEM_RECEIVED: "REWARD_FORM_ITEM_RECEIVED",
  REWARD_FORM_ITEM_REMOVED: "REWARD_FORM_ITEM_REMOVED",
  REWARD_FORM_ITEM_UPDATED: "REWARD_FORM_ITEM_UPDATED"
};
